name: CI-CD

on:
  push:
    branches: [ main ]

# 添加权限配置
permissions:
  contents: read
  packages: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      RAW_REPO: ${{ github.repository }}
    steps:
    - uses: actions/checkout@v4

    - name: Normalize image tag
      id: normalize
      run: |
        SAFE_REPO=$(echo "${RAW_REPO}" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
        echo "safe_repo=$SAFE_REPO" >> $GITHUB_OUTPUT

    - name: Install deps
      run: pip install -r requirements.txt
    # - run: pytest -q # 暂无测试

    - name: Build & Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ steps.normalize.outputs.safe_repo }}/myapi:${{ github.sha }}
        secrets: |
          GITHUB_TOKEN=${{ secrets.CR_PAT }}

  deploy:
    needs: test-build
    runs-on: ubuntu-latest
    env:
      RAW_REPO: ${{ github.repository }}
    steps:
    - name: Normalize image tag
      id: normalize
      run: |
        SAFE_REPO=$(echo "${RAW_REPO}" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
        echo "safe_repo=$SAFE_REPO" >> $GITHUB_OUTPUT

    - name: Run on Azure VM via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: root
        key: ${{ secrets.AZURE_SSH_KEY }}
        script: |
          docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.CR_PAT }}
          docker pull ghcr.io/${{ steps.normalize.outputs.safe_repo }}/myapi:${{ github.sha }}
          docker stop myapi || true && docker rm myapi || true
          docker run -d --name myapi -p 8000:8080 --restart always \
            ghcr.io/${{ steps.normalize.outputs.safe_repo }}/myapi:${{ github.sha }} 